language: python
python:
- '2.7'
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py26
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user:
    secure: I+lYiOMoB3QiCJ7V1O5AWg3FKN5cn6gHYfMsFIc9y6lTWvUci36O+Lw6RORsCsKJyhpIZYdNyNMZ4K5ddgTe/3OC3TXW88RaLWOB6z4c0Nznws8y4xxAN869U3xSp35rYsowU1NVNQts1Z8K8Tlgpn9gbhVmnpWp5Ak4g7oL03I=
  password:
    secure: ZgKxJ3qbU9LLT5lrFEdPFLpuUBQkyvYtOz63KnP7Pv/CrKZRJUoB3mecftmpEdwfenZk68g8pzUWDqRH7IkyIncVSfPeS/VfJMoXxzDHCjMCSEkQh1FMlyzQQsGcfBLNsQtvVJIpjUjuJTs37itj0MsQV01ns+6MNCuUbSsM1D0=
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v || exit 1
notifications:
  flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
